sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t soosungp33/docker-react-app-nginx -f Dockerfile.dev .

script:
  - docker run -e CI=true soosungp33/docker-react-app-nginx npm run test

after_success:
  - echo "Test success"